export ZSH=$HOME/.oh-my-zsh
export DEFAULT_USER=$(whoami)

ZSH_THEME="powerlevel9k/powerlevel9k"

# FONT: https://github.com/gabrielelana/awesome-terminal-fonts/tree/patching-strategy
#THEME: https://github.com/bhilburn/powerlevel9k
# POWERLEVEL9K_COLOR_SCHEME='light'
POWERLEVEL9K_MODE='awesome-patched'

TERM=xterm-256color

plugins=(git rails git brew bundler docker emoji rvm sublime)

# User configuration
export PATH="/usr/local/sbin:$HOME/.rvm/gems/ruby-2.1.3/bin:$HOME/.rvm/gems/ruby-2.1.3@global/bin:$HOME/.rvm/rubies/ruby-2.1.3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$HOME/.rvm/bin:/usr/local/share/dotnet/bin"

export MYSQL_PATH=/usr/local/Cellar/mysql/5.6.27
export PATH=$PATH:$MYSQL_PATH/bin

source $ZSH/oh-my-zsh.sh

alias be="bundle exec"

alias dlmp3="youtube-dl --extract-audio --audio-format mp3"

alias gs='git status'
alias gb='git branch'
alias gl='git log'
alias gc='git checkout'
alias gf='git fetch'
alias ga='git add'
alias grep='grep --color=auto'
alias clone='git clone'
alias cmt='git commit'
alias c='clear'

alias lll='ll -tra'

alias fetch='git fetch'
alias makettd='rm -rf bundle && ./configure --without-freetype LDFLAGS="-stdlib=libstdc++" && make -j8 && make bundle'

#SPOTIFY COMMANDS
alias play='spotify play'
alias pause='spotify pause'
alias stop='spotify stop'
alias next='spotify next &&  playing'
alias prev='spotify prev'
alias playing='spotify playing'
alias shuffle='spotify shuffle'

function serve () {
  SERVER_PORT=8080

  if [ $1 ]; then
    SERVER_PORT=$1
  fi

  http-server ./ -p ${SERVER_PORT}
}

function ip () {
  ifconfig | grep broadcast | awk '{print $2}' | head -n1
}

function psh () {
  git push origin -u `git branch | grep \* | sed 's/\* //'`
}

alias pushit="psh" # \m/ (>_<) \m/

function pushitrealgood () {
	git push origin -u -f (git branch | grep \* | sed 's/\* //')
}

# Pull the current directory
function pll () {
  git pull origin `git branch | grep \* | sed 's/\* //'`
}


alias gt="node_modules/karma/bin/karma start spec/config/karma.conf.js"


function specs () {
  if [ -n "$1" ]
  then
    if bundle exec rspec "$1"
    then
      unicornleap -s 2
    else
      unicornleap -s 2 -t
    fi
  else
    if bundle exec rspec
    then
      unicornleap -s 2
    else
      unicornleap -s 2 -t
    fi
  fi
}

function growl(){
  terminal-notifier -activate com.googlecode.iterm2 -title "Pssssst !!" -subtitle "A message from your shell:" -message "$1"
}

function growlsay(){
	if type "terminal-notifier" > /dev/null; then
		terminal-notifier -activate com.googlecode.iterm2 -title "Pssssst !!" -subtitle "A message from your shell:" -message "$1"
  elif type "notify-send" > /dev/null; then
		notify-send "Pssssst, A message from your shell:" "$1" -i face-wink
	fi
	echo $1 | cowsay -n -f dragon-and-cow | lolcat
  say "$1"
}

[ -s "$HOME/.dnx/dnvm/dnvm.sh" ] && . "$HOME/.dnx/dnvm/dnvm.sh" # Load dnvm
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"

# Load zsh-syntax-highlighting.
source ~/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Load zsh-autosuggestions.
source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh

# Base16 Shell
BASE16_SHELL="$HOME/.config/base16-shell/base16-flat.dark.sh"
[[ -s $BASE16_SHELL ]] && source $BASE16_SHELL

# Enable autosuggestions automatically.
# zle-line-init() {
#     zle autosuggest-start
# }
# zle -N zle-line-init

bindkey '^T' autosuggest-toggle

bindkey "^[[H" beginning-of-line
bindkey "^[[F" end-of-line

eval "$(thefuck --alias)"

code () { VSCODE_CWD="$PWD" open -n -b "com.microsoft.VSCode" --args $* ;}

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

if test -f ~/.gnupg/.gpg-agent-info -a -n "$(pgrep gpg-agent)"; then
  source ~/.gnupg/.gpg-agent-info
  export GPG_AGENT_INFO
else
  eval $(gpg-agent --daemon --write-env-file ~/.gnupg/.gpg-agent-info)
fi
